using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Linq;
using System.Windows.Forms;
using SoftwareNinjas.BranchAndReviewTools.Core;
using SoftwareNinjas.BranchAndReviewTools.Gui.Extensions;
using SoftwareNinjas.BranchAndReviewTools.Gui.Grids;
using SoftwareNinjas.Core;

namespace SoftwareNinjas.BranchAndReviewTools.Gui
{
    public partial class ChangeInspector : UserControl
    {
        public event SplitterEventHandler HorizontalDividerSplitterMoved;
        public event SplitterEventHandler VerticalDividerSplitterMoved;

        private object _context;

        public ChangeInspector()
        {
            InitializeComponent();
            ChangeLog.InitializeDefaults();
            PatchViewer.InitializeDefaults();
            PatchViewer.InitializeDiff();
            PatchViewer.KeyUp += PatchViewer_KeyUp;
            FileGrid.Grid.MultiSelect = true;
        }

        void PatchViewer_KeyUp(object sender, KeyEventArgs e)
        {
            if (e.KeyValue == 107 || e.KeyValue == 109)
            {
                PatchViewer.NativeInterface.ToggleFold(PatchViewer.GetCurrentLineNumber());
            }
        }

        [SettingsBindable(true)]
        public int VerticalDividerSplitterDistance
        {
            get { return verticalDivider.SplitterDistance; }
            set { verticalDivider.SplitterDistance = value; }
        }

        [SettingsBindable(true)]
        public int HorizontalDividerSplitterDistance
        {
            get { return horizontalDivider.SplitterDistance; }
            set { horizontalDivider.SplitterDistance = value; }
        }

        public string PatchText
        {
            get { return PatchViewer.Text; }
            set { PatchViewer.SetReadOnlyText(value); }
        }

        public object Context {
            get { return _context; }
            set
            { 
                _context = value;
                RefreshMessage();
                RefreshFileGrid();
            }
        }

        // given a Context (the current BranchId in the "Pending Changes" case and the current revision in "Log"),
        // produces a table of the changes involved
        public Func<object, DataTable> ChangesFunction { get; set; }
        internal DataTable GetChanges(object contextId)
        {
            return contextId != null && ChangesFunction != null ? ChangesFunction(contextId) : null;
        }

        // given one or more "ID"s from the table generated by ChangesFunction, produces a patch
        public Func<object, IEnumerable<object>, string> ComputeDifferencesFunction { get; set; }
        internal string ComputeDifferences(object contextId, IEnumerable<object> selectedIds)
        {
            return contextId != null && ComputeDifferencesFunction != null
                ? ComputeDifferencesFunction(contextId, selectedIds) : String.Empty;
        }

        public Func<object, IEnumerable<object>, IList<MenuAction>> ActionsForChangesFunction { get; set; }
        internal IList<MenuAction> GetActionsForChanges(object contextId, IEnumerable<object> selectedIds)
        {
            return contextId != null && ActionsForChangesFunction != null
                ? ActionsForChangesFunction(contextId, selectedIds) : MenuAction.EmptyList;
        }

        public Func<object, string> MessageFunction { get; set; }
        internal string GetMessage(object contextId)
        {
            return contextId != null && MessageFunction != null ? MessageFunction(contextId) : null;
        }

        public void RefreshMessage()
        {
            var message = GetMessage(_context) ?? String.Empty;
            if (this.ChangeLog.IsReadOnly)
            {    
                this.ChangeLog.SetReadOnlyText(message);
            }
            else
            {
                this.ChangeLog.Text = message;
            }
        }

        #region FileGrid
        public void RefreshFileGrid()
        {
            var pendingChanges = GetChanges(_context);
            FileGrid.DataTable = pendingChanges;
            var itemCount = FileGrid.Grid.Rows.Count;
            if (0 == itemCount)
            {
                PatchText = String.Empty;
            }
            FileGrid.Caption = "{0} changed item{1}".FormatInvariant(itemCount, itemCount == 1 ? "" : "s");
        }

        private IEnumerable<object> FindSelectedIds()
        {
            var selectedRows = FileGrid.Grid.SelectedRows;
            return selectedRows.Map(row => row.DataRow["ID"]);
        }

        void FileGrid_ContextMenuStripNeeded(object sender, ContextMenuNeededEventArgs e)
        {
            var menu = BuildChangedFilesActionMenu();
            e.ContextMenu = menu;
        }

        void FileGrid_SelectionChanged(object sender, EventArgs e)
        {
            var selectedIds = FindSelectedIds();
            var patch = ComputeDifferences(Context, selectedIds);
            PatchText = patch;
        }

        private ContextMenu BuildChangedFilesActionMenu()
        {
            var selectedIds = FindSelectedIds();
            var actions = GetActionsForChanges(Context, selectedIds);
            var menu = new ContextMenu();
            menu.MenuItems.AddActions(actions);
            return menu;
        }

        private void InvokeDefaultChangedFilesAction()
        {
            var menu = BuildChangedFilesActionMenu();
            menu.MenuItems.InvokeFirstMenuItem();
        }

        void FileGrid_RowInvoked(object sender, EventArgs e)
        {
            InvokeDefaultChangedFilesAction();
        }
        #endregion

        private void horizontalDivider_SplitterMoved(object sender, SplitterEventArgs e)
        {
            if (HorizontalDividerSplitterMoved != null)
            {
                HorizontalDividerSplitterMoved(this, e);
            }
        }

        private void verticalDivider_SplitterMoved(object sender, SplitterEventArgs e)
        {
            if (VerticalDividerSplitterMoved != null)
            {
                VerticalDividerSplitterMoved(this, e);
            }
        }
    }
}
