//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareNinjas.BranchAndReviewTools.Gui.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point WindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["WindowLocation"]));
            }
            set {
                this["WindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115")]
        public int branchGridAndRestDividerSplitterDistance {
            get {
                return ((int)(this["branchGridAndRestDividerSplitterDistance"]));
            }
            set {
                this["branchGridAndRestDividerSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115")]
        public int activityTopBottomPanelSplitterDistance {
            get {
                return ((int)(this["activityTopBottomPanelSplitterDistance"]));
            }
            set {
                this["activityTopBottomPanelSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("85")]
        public int activityChangeInspectorHorizontalDividerSplitterDistance {
            get {
                return ((int)(this["activityChangeInspectorHorizontalDividerSplitterDistance"]));
            }
            set {
                this["activityChangeInspectorHorizontalDividerSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("242")]
        public int activityChangeInspectorVerticalDividerSplitterDistance {
            get {
                return ((int)(this["activityChangeInspectorVerticalDividerSplitterDistance"]));
            }
            set {
                this["activityChangeInspectorVerticalDividerSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int pendingChangesHorizontalDividerSplitterDistance {
            get {
                return ((int)(this["pendingChangesHorizontalDividerSplitterDistance"]));
            }
            set {
                this["pendingChangesHorizontalDividerSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("273")]
        public int pendingChangesVerticalDividerSplitterDistance {
            get {
                return ((int)(this["pendingChangesVerticalDividerSplitterDistance"]));
            }
            set {
                this["pendingChangesVerticalDividerSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("115")]
        public int shelvesetGridAndRestDividerSplitterDistance {
            get {
                return ((int)(this["shelvesetGridAndRestDividerSplitterDistance"]));
            }
            set {
                this["shelvesetGridAndRestDividerSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("85")]
        public int shelvesetChangeInspectorHorizontalDividerSplitterDistance {
            get {
                return ((int)(this["shelvesetChangeInspectorHorizontalDividerSplitterDistance"]));
            }
            set {
                this["shelvesetChangeInspectorHorizontalDividerSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("273")]
        public int shelvesetChangeInspectorVerticalDividerSplitterDistance {
            get {
                return ((int)(this["shelvesetChangeInspectorVerticalDividerSplitterDistance"]));
            }
            set {
                this["shelvesetChangeInspectorVerticalDividerSplitterDistance"] = value;
            }
        }
    }
}
